FROM rocker/r-ver:3.4.4

ENV DEBIAN_FRONTEND=noninteractive

# System libraries required by R packages
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libgit2-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libcairo2-dev \
    libxt-dev \
    libglu1-mesa-dev \
    libgl1-mesa-dev \
    libv8-dev \
    libpoppler-cpp-dev \
    libglpk-dev \
    libmagick++-dev \
    libudunits2-dev \
    qpdf \
    antiword \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

# Freeze CRAN snapshot to match R 3.4.4 era
RUN echo "options(repos = c(CRAN='https://mran.microsoft.com/snapshot/2018-03-15'))" >> /usr/local/lib/R/etc/Rprofile.site

# Install R packages one by one
RUN R -e "install.packages('antiword', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('askpass', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('assertthat', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('backports', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('BH', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('bitops', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('bmp', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('brew', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('Cairo', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('callr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('caTools', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('cellranger', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('cli', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('clipr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('clisymbols', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('colorspace', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('commonmark', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('covr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('crayon', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('crosstalk', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('curl', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('data.table', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('desc', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('devtools', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('digest', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('downloader', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('DT', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('e1071', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('ellipsis', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('evaluate', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('fansi', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('farver', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('fastmap', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('foreach', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('formatR', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('fs', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('futile.logger', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('futile.options', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('ggplot2', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('gh', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('git2r', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('glmnet', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('glue', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('gtable', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('hms', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('htmltools', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('htmlwidgets', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('httpuv', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('httr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('igraph', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('imager', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('ini', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('ipred', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('irlba', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('iterators', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('jpeg', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('jsonlite', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('labeling', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('lambda.r', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('later', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('lava', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('lazyeval', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('lifecycle', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('magrittr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('maxent', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('memoise', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('mime', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('mlapi', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('munsell', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('ndjson', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('NLP', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('numDeriv', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('openssl', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('pdftools', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('pillar', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('pkgbuild', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('pkgconfig', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('pkgload', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('plyr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('png', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('praise', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('prettyunits', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('processx', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('prodlim', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('progress', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('promises', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('ps', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('purrr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('qpdf', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('R6', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('randomForest', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('rcmdcheck', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('RColorBrewer', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('Rcpp', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('RcppParallel', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('RCurl', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('readbitmap', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('readODS', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('readr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('readtext', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('readxl', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('rematch', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('remotes', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('reshape2', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('rex', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('rjson', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('rlang', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('roxygen2', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('rprojroot', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('rstudioapi', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('rversions', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('scales', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('sessioninfo', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('shiny', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('slam', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('SnowballC', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('sourcetools', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('SparseM', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('sparsepp', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('SQUAREM', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('streamR', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('stringi', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('stringr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('striprtf', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('sys', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('tau', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('testthat', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('text2vec', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('tibble', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('tiff', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('tm', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('tree', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('usethis', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('utf8', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('vctrs', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('viridisLite', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('whisker', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('withr', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('xgboost', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('xml2', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('xopen', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('xtable', dependencies=TRUE, Ncpus=4)"
RUN R -e "install.packages('yaml', dependencies=TRUE, Ncpus=4)"